from __future__ import annotations

from models import EnvironmentalEvent, RegionDefinition, ScenarioPreset


def _regions(
    africa_bias: float,
    corridor_bias: float,
    eurasia_bias: float,
) -> tuple[RegionDefinition, ...]:
    return (
        RegionDefinition(
            identifier="africa_core",
            label="Africa Core",
            center_x=0.19,
            center_y=0.44,
            spread_x=0.12,
            spread_y=0.16,
            carrying_capacity=185,
            habitat_quality=1.08,
            allele_bias=africa_bias,
            color="#7a9e3a",
            polygon=(
                (0.06, 0.20),
                (0.18, 0.13),
                (0.28, 0.19),
                (0.31, 0.35),
                (0.23, 0.61),
                (0.14, 0.74),
                (0.07, 0.54),
            ),
            neighbors=("corridor",),
        ),
        RegionDefinition(
            identifier="corridor",
            label="Northeast Corridor",
            center_x=0.48,
            center_y=0.33,
            spread_x=0.11,
            spread_y=0.10,
            carrying_capacity=90,
            habitat_quality=0.88,
            allele_bias=corridor_bias,
            color="#b0b96c",
            polygon=(
                (0.30, 0.24),
                (0.45, 0.18),
                (0.61, 0.20),
                (0.66, 0.31),
                (0.58, 0.45),
                (0.37, 0.42),
            ),
            neighbors=("africa_core", "eurasia"),
        ),
        RegionDefinition(
            identifier="eurasia",
            label="Eurasia",
            center_x=0.79,
            center_y=0.34,
            spread_x=0.15,
            spread_y=0.16,
            carrying_capacity=155,
            habitat_quality=1.0,
            allele_bias=eurasia_bias,
            color="#d5c88a",
            polygon=(
                (0.61, 0.18),
                (0.78, 0.10),
                (0.94, 0.16),
                (0.97, 0.31),
                (0.90, 0.50),
                (0.75, 0.58),
                (0.61, 0.43),
            ),
            neighbors=("corridor",),
        ),
    )


def load_presets() -> list[ScenarioPreset]:
    """Return scientifically inspired but explicitly simplified scenarios."""

    return [
        ScenarioPreset(
            name="Baseline / Out of Africa",
            category_label="Illustrative baseline",
            description=(
                "Most founders begin in an Africa-like core, then spread gradually through a "
                "lower-capacity corridor toward Eurasia as local density rises."
            ),
            disclaimer="Not a reconstruction of real prehistory; only an illustrative baseline.",
            seed=11,
            initial_population=140,
            genome_loci=24,
            group_target_size=16,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.24,
            migration_rate=0.050,
            long_distance_migration_rate=0.020,
            exogamy_rate=0.30,
            kin_avoidance=0.92,
            mortality_multiplier=1.0,
            fertility_multiplier=1.0,
            mate_search_radius=0.15,
            mate_genetic_diversity_weight=0.11,
            group_isolation_strength=0.32,
            group_fission_threshold=28,
            regions=_regions(0.28, 0.46, 0.66),
            initial_region_weights={"africa_core": 0.84, "corridor": 0.10, "eurasia": 0.06},
            events=(
                EnvironmentalEvent(
                    label="Corridor aridity pulse",
                    description="A modest corridor stress window that lowers carrying capacity and encourages movement.",
                    start_tick=32,
                    end_tick=44,
                    migration_multiplier=1.10,
                    region_capacity_multipliers={"corridor": 0.82},
                    region_migration_push={"corridor": 0.15},
                    map_color="#c97d3e",
                ),
            ),
        ),
        ScenarioPreset(
            name="Deep bottleneck hypothesis",
            category_label="Hypothesis",
            description=(
                "Begins with a very small founder pool and a prolonged low-capacity phase. "
                "This is included as a hypothesis test, not as settled history."
            ),
            disclaimer=(
                "The deep bottleneck framing is controversial and is shown here only as a "
                "simplified hypothesis."
            ),
            seed=23,
            initial_population=48,
            genome_loci=24,
            group_target_size=12,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.23,
            migration_rate=0.036,
            long_distance_migration_rate=0.012,
            exogamy_rate=0.18,
            kin_avoidance=0.88,
            mortality_multiplier=1.08,
            fertility_multiplier=0.96,
            mate_search_radius=0.13,
            mate_genetic_diversity_weight=0.08,
            group_isolation_strength=0.50,
            group_fission_threshold=24,
            regions=_regions(0.30, 0.45, 0.65),
            initial_region_weights={"africa_core": 0.88, "corridor": 0.10, "eurasia": 0.02},
            events=(
                EnvironmentalEvent(
                    label="Extended low-capacity window",
                    description="Long period of depressed resources and slower demographic recovery.",
                    start_tick=0,
                    end_tick=30,
                    mortality_multiplier=1.12,
                    fertility_multiplier=0.92,
                    capacity_multiplier=0.78,
                    region_capacity_multipliers={"corridor": 0.70},
                    region_migration_push={"corridor": 0.10},
                    map_color="#bc6c25",
                ),
            ),
        ),
        ScenarioPreset(
            name="Toba-style environmental stress hypothesis",
            category_label="Hypothesis",
            description=(
                "Applies a temporary, severe environmental shock with lower carrying capacity, "
                "lower fertility, higher mortality, and stronger displacement."
            ),
            disclaimer=(
                "This does not claim that any specific eruption produced a human near-extinction; "
                "it is an explicit stress hypothesis."
            ),
            seed=37,
            initial_population=135,
            genome_loci=24,
            group_target_size=16,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.24,
            migration_rate=0.058,
            long_distance_migration_rate=0.028,
            exogamy_rate=0.28,
            kin_avoidance=0.92,
            mortality_multiplier=1.0,
            fertility_multiplier=1.0,
            mate_search_radius=0.15,
            mate_genetic_diversity_weight=0.10,
            group_isolation_strength=0.36,
            group_fission_threshold=28,
            regions=_regions(0.28, 0.46, 0.66),
            initial_region_weights={"africa_core": 0.80, "corridor": 0.12, "eurasia": 0.08},
            events=(
                EnvironmentalEvent(
                    label="Shock onset",
                    description="Short severe shock with major corridor and Eurasia stress.",
                    start_tick=18,
                    end_tick=25,
                    mortality_multiplier=1.42,
                    fertility_multiplier=0.68,
                    migration_multiplier=1.45,
                    capacity_multiplier=0.76,
                    region_capacity_multipliers={
                        "africa_core": 0.82,
                        "corridor": 0.56,
                        "eurasia": 0.52,
                    },
                    region_mortality_multipliers={
                        "corridor": 1.18,
                        "eurasia": 1.16,
                    },
                    region_fertility_multipliers={
                        "corridor": 0.82,
                        "eurasia": 0.85,
                    },
                    region_migration_push={
                        "corridor": 0.35,
                        "eurasia": 0.22,
                    },
                    map_color="#cf5c36",
                ),
                EnvironmentalEvent(
                    label="Slow recovery",
                    description="Capacity partially recovers, but fertility and corridor quality stay depressed for a while.",
                    start_tick=26,
                    end_tick=40,
                    fertility_multiplier=0.88,
                    migration_multiplier=1.12,
                    region_capacity_multipliers={"corridor": 0.78, "eurasia": 0.84},
                    region_migration_push={"corridor": 0.10},
                    map_color="#e09f3e",
                ),
            ),
        ),
        ScenarioPreset(
            name="Structured ancestry",
            category_label="Illustrative structure",
            description=(
                "Maintains stronger regional structure and lower inter-region gene flow so "
                "that ancestry remains subdivided for longer."
            ),
            disclaimer=(
                "This is an illustrative structured-population setup, not a claim that one "
                "specific ancestral graph is correct."
            ),
            seed=41,
            initial_population=165,
            genome_loci=24,
            group_target_size=15,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.24,
            migration_rate=0.030,
            long_distance_migration_rate=0.010,
            exogamy_rate=0.16,
            kin_avoidance=0.93,
            mortality_multiplier=1.0,
            fertility_multiplier=1.0,
            mate_search_radius=0.12,
            mate_genetic_diversity_weight=0.07,
            group_isolation_strength=0.62,
            group_fission_threshold=24,
            regions=_regions(0.18, 0.50, 0.82),
            initial_region_weights={"africa_core": 0.55, "corridor": 0.20, "eurasia": 0.25},
            events=(
                EnvironmentalEvent(
                    label="Corridor contraction",
                    description="Temporarily narrows the effective corridor and reduces exchange across regions.",
                    start_tick=45,
                    end_tick=60,
                    migration_multiplier=0.92,
                    region_capacity_multipliers={"corridor": 0.72},
                    region_migration_push={"corridor": 0.12},
                    map_color="#b56576",
                ),
            ),
        ),
        ScenarioPreset(
            name="Low exogamy stress test",
            category_label="Exploratory stress test",
            description=(
                "Suppresses inter-group mate exchange and reduces kin avoidance to probe how "
                "quickly related-pair detections rise in small local groups."
            ),
            disclaimer="This is an exploration of model behavior, not a historical claim.",
            seed=53,
            initial_population=120,
            genome_loci=24,
            group_target_size=14,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.23,
            migration_rate=0.016,
            long_distance_migration_rate=0.004,
            exogamy_rate=0.05,
            kin_avoidance=0.72,
            mortality_multiplier=1.0,
            fertility_multiplier=1.0,
            mate_search_radius=0.10,
            mate_genetic_diversity_weight=0.03,
            group_isolation_strength=0.78,
            group_fission_threshold=22,
            regions=_regions(0.28, 0.46, 0.66),
            initial_region_weights={"africa_core": 0.82, "corridor": 0.12, "eurasia": 0.06},
        ),
        ScenarioPreset(
            name="Inbreeding stress test",
            category_label="Experimental stress test",
            description=(
                "Very small starting population with weak dispersal, low exogamy, strong group isolation, "
                "and no kin avoidance, intended to explore when inbreeding becomes hard to avoid."
            ),
            disclaimer="This is an experimental sandbox scenario designed to expose inbreeding pressure.",
            seed=67,
            initial_population=72,
            genome_loci=24,
            group_target_size=10,
            adult_age=16,
            menopause_age=40,
            max_age=72,
            birth_interval=3,
            annual_birth_probability=0.22,
            migration_rate=0.006,
            long_distance_migration_rate=0.002,
            exogamy_rate=0.03,
            kin_avoidance=0.0,
            mortality_multiplier=1.02,
            fertility_multiplier=0.98,
            mate_search_radius=0.08,
            mate_genetic_diversity_weight=0.02,
            group_isolation_strength=0.90,
            group_fission_threshold=16,
            regions=_regions(0.30, 0.47, 0.64),
            initial_region_weights={"africa_core": 0.92, "corridor": 0.08, "eurasia": 0.0},
            events=(
                EnvironmentalEvent(
                    label="Persistent isolation",
                    description="Low exchange keeps small local groups reproductively constrained for an extended period.",
                    start_tick=0,
                    end_tick=120,
                    migration_multiplier=0.82,
                    region_capacity_multipliers={"corridor": 0.88},
                    region_migration_push={"corridor": 0.05},
                    map_color="#9b2226",
                ),
            ),
        ),
    ]
